### ISSUE TITLE
Issue when using dataFunction and null object returned

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#1]
When the dataFunction's function returns a null result jQuery throws an exception as well the pager next and previous buttons are displayed.  What might be a cool option is to have a noData template where you can specify a HTML template to be displayed in the target div to display some message about no data being present.

**Comment by JamesRandall** [comment]
Thats a good idea - I will look into it.

**Comment by JamesRandall** [comment]
This should now work. There is an emptyTemplate that if you supply and null is returned from the function (and you're on the first page) then the template is shown. In v0.6.0.0 in the development branch.
