### ISSUE TITLE
pagenumber

### ISSUE THREAD

**Issue by c941010623** [JamesRandall/Simple-Paging-Grid#10]
when i insert some data to Array

then i use $("#exampleGrid").simplePagingGrid("refresh");

the exampleGrid will show new data but when data length >10

pagenumber will not add +1

ex: 1,2,3,4, not add 5

**Comment by c941010623** [comment]
i try simplePagingGrid-0.5.0.1.js

then i Modify #147

_numberOfPages: function () {
            if (this._numberOfRows !== null) {
                this._numberOfRows = this._sourceData.currentPage.length;
                return Math.ceil(this._numberOfRows / this._settings.pageSize);
            }
            return Number.MAX_VALUE;
        },

it's work when data Array push >10 than pagenumber auto +1

**Comment by c941010623** [comment]
BUG 
var rows=[];

when i change rows data then i use $("#exampleGrid").simplePagingGrid("refresh");

it's not work

**Comment by JamesRandall** [comment]
Thanks for this info. I must admit I hadn't really focussed on the array binding and refresh as I'd (in my head at least) only really intended it for URLs assuming arrays would be static.

It ought to work though. I'll work your fix in and look at the second bug and roll them into the upcoming 0.5.0.2 (mostly a set of unit tests and a few bug fixes)

**Comment by c941010623** [comment]
Thank you very much look forward to your new version

**Comment by c941010623** [comment]
i Hope the bug will fix

i need you ....

**Comment by JamesRandall** [comment]
Hi - sorry I've had a really busy week or two. I should be able to work on this tomorrow.

**Comment by JamesRandall** [comment]
This should all work now in 0.5.0.2 (development branch).

I've updated the documentation and added a new example that illustrates how to do paging with a data array. There are also some unit tests you could take a look at.

If you have any more issues let me know!
