### ISSUE TITLE
First / Last paging buttons displayed when no paging exists

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#11]
I have noticed that when using a data array as the source and when there is only one page visible the First and Last buttons are displayed.

Not a big deal but it would be nice if the grid could be configured to either turn off paging completely (pagingEnabled: false/true) via options or if based on the number of pages calculated > 1 then display the paging bar.

Thoughts?
William

**Comment by JamesRandall** [comment]
Makes sense. I'll look to put that in a future version.

**Comment by JamesRandall** [comment]
I've added a pagingEnabled property that will allow you to turn the paging bar off.

**Comment by JamesRandall** [comment]
(To add - at the time of writing it's in the development branch in version 0.6.0.0)
