### ISSUE TITLE
Cell template does not work

### ISSUE THREAD

**Issue by olegrb** [JamesRandall/Simple-Paging-Grid#13]
Hello,
In the last Simple-Paging-Grid version: 0.5.0.2 (with the last "handlebars" library version) the cellTemplates functionality seems to be "broken".

**Comment by JamesRandall** [comment]
Hi - I'll take a look in the next few days. Do you have any more details and / or an example? Or does it just not work full stop (I thought it did as the examples use it, but if I'm wrong please let me know).

**Comment by olegrb** [comment]
Hi, Thank you very much for the quick response.

It seems like the "cellTemplates" functionality gets broken after refresh.
If i try to load data into the Grid at initial state (while creating it) the "cellTemplates" functionality is OK, but after data refresh only "Not Templated" (template set to null) columns are displayed. 

Regards,

**Comment by JamesRandall** [comment]
Thanks for the additional info. I'll get that fixed and some unit tests added to cover it.

**Comment by JamesRandall** [comment]
Sorry for the delay in looking this - suffered a nasty migraine which set me back a little. Will get to it shortly I hope.

**Comment by olegrb** [comment]
Hi ! I hope you feel well now.
I made a little research and found out the following: 
In function "_deferredCellTemplateCompilation" the "that._compiledCellTemplates === null" condition prevents from entering the "if" segment 
In which the cellTempleate is reinitialized …
