### ISSUE TITLE
Safety checking for accessing cellContainerTemplates is incorrect

### ISSUE THREAD

**Issue by markanprice** [JamesRandall/Simple-Paging-Grid#15]
The current safety code checks that the array is not null, checks that the specified element is within array length and then checks that the array is not null again rather than checking that the specified element is not null (around line 552 in v0.5.0.2).

Line of code (wrapped):

if (that._settings.cellContainerTemplates !== null && index < that._settings.cellContainerTemplates.length && that._settings.cellContainerTemplates !== null) {

should read (also wrapped):

if (that._settings.cellContainerTemplates !== null && index < that._settings.cellContainerTemplates.length && that._settings.cellContainerTemplates[index] !== null) {

?

**Comment by JamesRandall** [comment]
Thanks! Fixed in v0.6.0.0 (currently in development branch).
