### ISSUE TITLE
rowTemplates option

### ISSUE THREAD

**Issue by olegrb** [JamesRandall/Simple-Paging-Grid#16]
Hello Randel,
I have a small question. 
Is it possible to use rowTemplates option to supply an onClick function to each grid row ?
E.G Something like that onclick='onCasesTableRowClick('{{id}}')
If yes , what be the proper template definition ?

Best Regards

**Comment by JamesRandall** [comment]
Hi,

The best way to do this at the moment is to supply a function to the pageRenderedEvent. This is called when the page is rendered and in their you can grab hold of the rows from the grid by using normal jQuery syntax.

The event is supplied the data that composes the page so you can fish out any IDs you need from their or from data-id type tags you post into the HTML.

Hope that helps.
