### ISSUE TITLE
HTML code in header title/template

### ISSUE THREAD

**Issue by pawelgorczynski** [JamesRandall/Simple-Paging-Grid#17]
Hi,
we've recently started using your grid and it seems quite cool :)

Though we have the following issue:
when one of the column in 'columnNames' contains html code, then it displays as normal string.

What even more strange, when I pasted the same code in 'headerTemplate' it appears fine.. and only in the first column...

This behavior is a bit odd...

**Comment by JamesRandall** [comment]
Hi - yes that seems a bit odd. I've been real busy lately but I'll take a look.

**Comment by pawelgorczynski** [comment]
Hi,
on the second part - it turned out that the first column was not sortable, while others were ;)

But still using html as the column name would be a nice feature but there's something strange going on.

**Comment by JamesRandall** [comment]
I'll definitely take a look at that - it ought to support HTML as the column name but I bet I've mixed up my escaping between the strings and the templating at some point.

**Comment by JamesRandall** [comment]
Hi,

In the development branch is a 0.6.0.0 version where I've tested some of this. In older versions where handlerbars wasn't used so extensively I think the above was an issue but it no longer is.

If you drop special characters (such as html tags) into the columnNames array then these will be displayed as plain text.

If you want to customize the HTML use the headerTemplates property in the same way as you would the cellTemplates property.

Here's an example of setting the first column to red:

headerTemplates: ['<th width="{{width}}" style="background-color: red;">{{title}}</th>']

You can use the templates.headerTemplate property to change the default.

Hope that helps.
