### ISSUE TITLE
HTML special chars in a table cell

### ISSUE THREAD

**Issue by coppolafab** [JamesRandall/Simple-Paging-Grid#18]
Putting HTML special chars in a table cell may cause some troubles, since they corrupt its content.

Eg. 'my email &lt;my@email.com&gt;'

I have found that adding:

(line 561)
var value = (rowData[propertyName] == null) ? "" : rowData[propertyName].replace(/&amp;/g, "&amp;amp;").replace(/&lt;/g, "&amp;lt;").replace(/&gt;/g, "&amp;gt;");

fixes this issue.

**Comment by JamesRandall** [comment]
Thanks for reporting this. It's fixed on 0.6.0.0 - at the time of writing this comment that's in the development branch but I expect it to become the master version this weekend.
