### ISSUE TITLE
use in bootstrap 3.0 css will Breakage

### ISSUE THREAD

**Issue by c941010623** [JamesRandall/Simple-Paging-Grid#19]
can you help me use in bootstap 3.0 ??

**Comment by JamesRandall** [comment]
Hi,

I've not yet had to try it in bootstrap 3 but based on my other experiences with 3 I'm not surprised it breaks. I'll try and get an update out soon but very busy on a number of projects - would welcome pull requests!

**Comment by JamesRandall** [comment]
In the development branch is a version which works with Bootstrap 3. It was more painless than I thought to migrate.

I expect this version to become the main release this weekend.
