### ISSUE TITLE
Custom ajax requests

### ISSUE THREAD

**Issue by lo1tuma** [JamesRandall/Simple-Paging-Grid#3]
It would be nice if you can do a custom ajax request, in case that the server requires other parameter names for pagination.
A simple callback function for dataFunction which returns the data would do that.

**Comment by lo1tuma** [comment]
Example for dataFunction:

``` js
function (pageNumber, pageSize, sortColumn, sortOrder, callback) {
    $.post(myUrl, {searchQuery: query, limit: pageSize, start: pageNumber}.done(function(response)) {
       callback(response.data);
    });
}
```

**Comment by JamesRandall** [comment]
Thats a great suggestion - thanks.

I'll look to build it into the upcoming version (I'd hoped to get that out by now but I'm having to have a bit of a break).

**Comment by JamesRandall** [comment]
I've been thinking about this while working on 0.5 as I've been rubbing up against some friction caused by the existing binding / data retrieval approach and am going to replace it in 0.6. My expectation is to use a callback model and I think this will also address this.

**Comment by JamesRandall** [comment]
This is now in version 0.6.0.0 in the development branch (making it to master shortly).

The dataFunction properties function signature has changed to use a callback rather than returning the data - format is as per above.
