### ISSUE TITLE
Raise events / callbacks on grid

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#4]
When using the baked-in data url and paging it might be nice to have a callback or anon function when the data was loaded (passing the data back in) or just a way to know when the grid was attached to the DOM (complete(), load(data)).

**Comment by JamesRandall** [comment]
This should be part of 0.5 - there are a few construction / replace activities that take place and I'm exposing them all as events that gives a chance for events to be bound to templated HTML.

Will close issue when I put 0.5 live. For now its in development branch (eventTemplateCreated, gridCreated).

**Comment by JamesRandall** [comment]
In 0.5
