### ISSUE TITLE
Data context issue with Handlebars

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#5]
I found an issue with how the grid builds the rows with the context of the data being used.

For example when I make a post to the server to get paged data back I create the JSON object with the currentPage and totalRows properties, I also inject urls for dynamic loading popups and such based on the data returned.

With Handlebars you can move up the object tree by using {{../PROPERTY_NAME}} however due to how the grid only takes the paged data to generate the rows the context of the parent properties is lost.  While it may make sense for this, the issue is it breaks how one can utilize Handlebars in the template of the cells (or even that matter the header cells.

I could inject the urls in every row of the paged data but that is a step I do not want to take.

For me I would think that the entire context of data be available to the Handlebars engine.

Thoughts?

**Comment by JamesRandall** [comment]
I can see what you're trying to do - I'll have a think about what it might mean. Thanks for all the feedback btw, appreciated.

**Comment by JamesRandall** [comment]
I've still got some testing to do but this is now in 0.5. The templates now bind to your server object and have their row context set with the handlerbars with helper e.g. {{#with currentpage.[0]}} *\* your template *\* {{/with}}.

Will mark as closed when I publish 0.5 to master.

**Comment by JamesRandall** [comment]
In 0.5
