### ISSUE TITLE
numberOfPages returns incorrect number

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#6]
This function returns Number.MAX_VALUE when it should return 0.

The value of MAX_VALUE is 1.7976931348623157e+308 which does not make any sense, if the numberOfRows is null then I would suspect the data source is not going to implement paging since numberOfRows comes from the totalRows property on the object from the server.

Thoughts?

**Comment by JamesRandall** [comment]
I agree Number.MAX_VALUE is completely arbitary, and probably the result of me not thinking about it / using it in that scenario. I'll give it some thought.

**Comment by JamesRandall** [comment]
I've updated this to return 0 in v0.6.0.0
