### ISSUE TITLE
Setting initialSortColumn or sortOrder does not set sort indicator on grid load

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#7]
When setting these properties the sort order indicators should be setup as well.

Using IE9

**Comment by JamesRandall** [comment]
I'll get this fixed in 0.5

**Comment by JamesRandall** [comment]
Now fixed in 0.5, will mark closed when I move into master.

**Comment by JamesRandall** [comment]
In 0.5
