### ISSUE TITLE
Issue with loading from a Url

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#8]
I believe that I found a bug with the newest version, the issue is when you are loading the grid via a url and don't supply an empty template the grid throws a javascript error.

It can be repoduced using the sample MvcSearch example and commenting out the empty template.

**Comment by JamesRandall** [comment]
You're right, should now be fixed in the point release and NuGet package I've just released. Thanks for reporting as that had slipped by me.
