### ISSUE TITLE
Issue with emptyTemplate and updating the dataUrl

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#9]
Some context...

I am using log4net for my logger and I have setup a view to load the data using the dataUrl just like your sample search.  I have a dropdown for the log levels for log4net and have bound the change event of the dropdown to update the dataUrl with the "refresh" command on the grid.

What I have found is that when the grid loads for the first time if I select a log level that does not have any data the emptyTemplate loads fine however when I select a log level that has entries in it the grid calls the refresh with the updated dataUrl however the grid does not render any data rows.  If i then select a log level that does not have any data it still will show the emptyTemplate fine.

The issue is when the empty template loads and then you call the "refresh" to load data it seems like it is not appending the table structure.

Hopefully that makes sense.  If you need I can setup a sample site that shows what is happening.

**Comment by JamesRandall** [comment]
It does thanks.

I'll try and take a look today.

**Comment by JamesRandall** [comment]
I've replicated this with a unit test and I believe fixed it - it's in 0.5.0.2 in the development branch. If you could let me know if that does fix this in your specific scenario that would be great.

**Comment by wrhighfield** [comment]
I just tested it with the new branch and it seems to have fixed the issue.

Thanks
William

**Comment by JamesRandall** [comment]
Great! Thanks for that.

Fixed in 0.5.0.2 (currently in development branch).
